language: go
go:
  - 1.x

sudo: required
services:
  - docker

env:
  - GOVERSION=1.11

before_install:
  - chmod +x ./run_tests.sh

install: true

cache:
  directories:
    - ~/.cache

script:
  - ./run_tests.sh docker
