language: go
go:
  - 1.x

sudo: required
services:
  - docker

before_install:
  - chmod +x ./run_tests.sh

env:
  - GOVERSION=1.11

install: true

cache:
  directories:
    - ~/.cache

script:
  - rsync --version
  - sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y rsync
  - rsync --version
  - ls
  - ./run_tests.sh docker
